spring:
  application:
    name: hiring-challenge
  profiles:
    active: standalone
  datasource:
      url:  jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    format_sql: true
    hibernate:
        ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  version: HIRING

logging:
  level:
    root: ERROR
    com.itxiop: TRACE
    
graph:
#  folder: sameTruckTrainLocations
#  folder: noStopLocations
#  folder: multipleTransportTypes
   folder: noStopLocations



